### ISSUE TITLE
canTransform fails 9/10 times for color stream 1920x1080@30FPS and depth stream 480x360/640x480 @30FPS

### ISSUE THREAD

**Issue by rjingar** [ros/geometry2#177]
My nodelet is publishing color stream with 1920x1080:30FPS and depth stream 480x360/640x480:30FPS. It also publishes camera transforms for the streams. I checked transform tf tree in 'frames.pdf' generated using "rosrun tf view_frames" and everything looks good. Here is the screenshot for view_frames result:
![image](https://cloud.githubusercontent.com/assets/12900123/15436976/08f94c26-1e8a-11e6-9b6e-43e9500da052.png)

But when I try running canTransform in my unit test to verify transform, it fails 9 out of 10 times. Error message (error_msg) is always blank even when canTransform API fails. 

Here is the code snippet for unit test:
  EXPECT_TRUE(tf_listener.canTransform (DEPTH_DEF_FRAME, BASE_DEF_FRAME, ros::Time::now(), &error_msg));
  EXPECT_TRUE(tf_listener.canTransform (DEPTH_OPTICAL_DEF_FRAME, DEPTH_DEF_FRAME, ros::Time::now(), &error_msg));
  EXPECT_TRUE(tf_listener.canTransform (COLOR_DEF_FRAME, BASE_DEF_FRAME, ros::Time::now(), &error_msg));
  EXPECT_TRUE(tf_listener.canTransform (COLOR_OPTICAL_DEF_FRAME, COLOR_DEF_FRAME, ros::Time::now(), &error_msg));

With color stream resolution 1920x1080:30FPS and depth stream resolution 320x240:30FPS or any lower resolution for both the stream works fine. 

Is there any specific reason or buffer size restrictions that i am missing here?

**Comment by tfoote** [comment]
Can transform of `ros::Time::now()` would be expected to fail most of the time since the data for "now" is likely not available for some duration. Please review the [tf and time tutorials](http://wiki.ros.org/tf/Tutorials/tf%20and%20Time%20%28C%2B%2B%29) and if you have more questions please ask for help on answers.ros.org.

[tf2 version of the tutorial](http://wiki.ros.org/tf2/Tutorials/tf2%20and%20time%20%28C%2B%2B%29)
