### ISSUE TITLE
do_transform_vector3() alters the passed transformation

### ISSUE THREAD

**Issue by swagner91** [ros/geometry2#233]
I'm in a situation where i use a transformation to transform several objects pose, velocities and accelerations. The latter two are transformed by do_transform_vector3 as they must not be translated but only rotated. The problem is when looping over the objects, the fist call of do_transform_vector3 sets the translation parameters of the transformation to zero (see `tf2_geometry_msgs/tf2_geometry_msgs.py` lines 71 -73), making all upcoming calls of do_transform_pose using a wrong transformation. It can be quickly solved by wrapping the transformation in the function call with a `copy.deepcopy()` statement.

I'm not exactly sure if this can be regarded as an issue, but i do not think it is intuitive to have a transformation call alter my inputs.

**Comment by tfoote** [comment]
Yeah, that looks like unintuitive behavior it would be better to make a deep copy first. A PR to do that would be appreciated, otherwise I'll try to find time to do it myself. 

For reference the lines of code are at: https://github.com/ros/geometry2/blob/indigo-devel/tf2_geometry_msgs/src/tf2_geometry_msgs/tf2_geometry_msgs.py#L71-L73
