### ISSUE TITLE
when I call ros::init(argc,argv,"test")；the app report problem as the following.

### ISSUE THREAD

**Issue by loulansuiye** [ros/geometry2#323]
terminate called after throwing an instance of 'ros::TimeNotInitializedException'
  what():  Cannot use ros::Time::now() before the first NodeHandle has been created or ros::start() has been called.  If this is a standalone app or test that just uses ros::Time and does not communicate over ROS, you may also call ros::Time::init()

**Comment by tfoote** [comment]
@loulansuiye As mentioned here: https://github.com/ros/geometry/issues/30#issuecomment-415836793 and please ask for help on answers.ros.org following our support guidelines: http://wiki.ros.org/Support note that there is not enough information in this to reproduce your problem so we won't be able to help you much. And multiply posting your issue is considered bad etiquette.
