### ISSUE TITLE
tf2_ros - Realtime-safe TransformBroadcaster

### ISSUE THREAD

**Issue by matthew-reynolds** [ros/geometry2#332]
tf2_ros's `TransformBroadcaster::sendTransform` uses standard `ros::Publisher`s to publish transformations. This is fine when using tools like [robot_state_publisher](https://github.com/ros/robot_state_publisher), which spin up independant nodes to handle publishing transformations, but it makes it difficult to safely publish a transformation tree from within your main robot HW node (eg. RobotHW in ros_control). Perhaps the safest way to publish your transformations is in a dedicated node, but I believe there are cases where it may be prefered to publish the transformations from your realtime controller.

I'm proposing adding a `realtime_tools::RealtimePublisher` to the class, and creating accompanying `sendTransformRT` functions that provide the same functionality as their existing non-RT counterparts, but using the RT publisher instead. Alternatively, the existing ros::Publisher could be _replaced_ with the RealtimePublisher, and the existing functions adapted accordingly, although I'm more inclined to add behaviour than mess with existing, reliable behaviour.

One thing to note about my proposal is that the parity between C++ and Python would be lost, as [realtime_tools](https://github.com/ros-controls/realtime_tools) doesn't have Python libraries, it is a C++ only library package. This is understandable though, as Python is not a good candidate for realtime applications anyways (Neither is C++ really, but it is much more reasonable than Python). 

Note that due to the nature of `StaticTransformBroadcaster`, we likely don't need realtime safety here, hence my proposal to only add a RealtimePublisher to the non-static TransformBroadcaster. If desired, though, it is trivial to also add the RT version here.

If this feature is deemed acceptable I will submit a PR with the changes.

**Comment by tfoote** [comment]
I'd rather not add realtime_tools as a dependency of the core of tf2, because most users won't want to use it. Due to the simplicity of the transform broadcaster (implementation less than 20 lines of code.  I'd suggest making a duplicate class for the realtime implementation that could be added to the realtime_tools package which is where people doing realtime things would be looking for something like that. 

You would likely only be able to do the single transform publish, and not the convert into vector anyway to avoid memory allocations inherent to upcasting it to a vector.

**Comment by matthew-reynolds** [comment]
Makes a lot of sense, thanks! I'll move the request over to realtime_tools.
