### ISSUE TITLE
Two tf broadcasters in same node issue for Kinetic

### ISSUE THREAD

**Issue by brunoeducsantos** [ros/geometry2#406]
Hi,
For python version of tf2 in Kinetic version it occurs a kind of concurrency when publishing two broadcasters in the same node:

```
  tf_broadcaster = tf2_ros.StaticTransformBroadcaster()

    static_transformStamped = TransformStamped()

    static_transformStamped.header.stamp = rospy.Time.now()
    static_transformStamped.header.frame_id = "odom"
    static_transformStamped.child_frame_id = "camera_init"

    static_transformStamped.transform.translation.x = 0
    static_transformStamped.transform.translation.y = 0
    static_transformStamped.transform.translation.z = 0

    quat = tf_conversions.transformations.quaternion_from_euler(np.radians(90),0,np.radians(90))
    static_transformStamped.transform.rotation.x = quat[0]
    static_transformStamped.transform.rotation.y = quat[1]
    static_transformStamped.transform.rotation.z = quat[2]
    static_transformStamped.transform.rotation.w = quat[3]

    tf_broadcaster.sendTransform(static_transformStamped)

 
    tf_broadcaster = tf2_ros.StaticTransformBroadcaster()
    static_transformStamped2 = TransformStamped()

    static_transformStamped2.header.stamp = rospy.Time.now()
    static_transformStamped2.header.frame_id = "camera"
    static_transformStamped2.child_frame_id = "base_link"

    static_transformStamped2.transform.translation.x = 0
    static_transformStamped2.transform.translation.y = 0
    static_transformStamped2.transform.translation.z = 0

    quat = tf_conversions.transformations.quaternion_from_euler(-np.radians(90),-np.radians(90),0)
    static_transformStamped2.transform.rotation.x = quat[0]
    static_transformStamped2.transform.rotation.y = quat[1]
    static_transformStamped2.transform.rotation.z = quat[2]
    static_transformStamped2.transform.rotation.w = quat[3]
    tf_broadcaster.sendTransform(static_transformStamped2)
```

![image](https://user-images.githubusercontent.com/3111976/63588935-9b732f80-c59f-11e9-8d99-436e1681876e.png)

Anyone has a suggestion or PR to solve this?

Regards,
Bruno

**Comment by Timple** [comment]
For future reference:

This is because a `tf2_ros.StaticTransformBroadcaster()` is in fact simply a latched publisher on the `/tf_static` topic.

And according to the [wiki](http://wiki.ros.org/roscpp/Overview/Publishers%20and%20Subscribers):

> latch [optional]
Enables "latching" on a connection. When a connection is latched, the last message published is saved and automatically sent to any future subscribers that connect. This is useful for slow-changing to static data like a map. **Note that if there are multiple publishers on the same topic, instantiated in the same node, then only the last published message from that node will be sent, as opposed to the last published message from each publisher on that single topic.**

One solution would (obviously) be to use only one `tf2_ros.StaticTransformBroadcaster()` per node.
