### ISSUE TITLE
Issue compiling from source on kinetic. logWarn and logError

### ISSUE THREAD

**Issue by lavancig** [ros/geometry2#413]
File has old definitions of logWarn and logError. Adding CONSOLE_BRIDGE_ solves it for me.

https://github.com/ros/geometry2/blob/3c51d5936805512888bd8ee2893f1de22b287829/tf2/src/buffer_core.cpp#L126

**Comment by tfoote** [comment]
We're building and running CI on kinetic. Please explain your setup and why it's not working. This is patched in the melodic-devel branch which supports the newer API https://github.com/ros/geometry2/blob/1cbda1e145a1214920c9448ffd8b753bf866df67/tf2/src/buffer_core.cpp#L126

**Comment by jveitchmichaelis** [comment]
If you follow the standard install for Kinetic (e.g. the install generator), it pulls the Kinetic release of tf2, but presumably a newer version of Console Bridge. The kinetic release could be updated with a macro fix like:

https://github.com/ros-gbp/geometry2-release/issues/2

From my .rosinstall

```
local-name: rosconsole_bridge
    uri: https://github.com/ros-gbp/rosconsole_bridge-release/archive/release/kinetic/rosconsole_bridge/0.5.2-0.tar.gz
    version: rosconsole_bridge-release-release-kinetic-rosconsole_bridge-0.5.2-0

local-name: geometry2/tf2_ros
    uri: https://github.com/ros-gbp/geometry2-release/archive/release/kinetic/tf2_ros/0.5.20-0.tar.gz
    version: geometry2-release-release-kinetic-tf2_ros-0.5.20-0
```

I'm running this in a Debian buster image on Arm64 in a Docker container:

```
rosinstall_generator robot --rosdistro kinetic --deps --wet-only --tar
```

**Comment by tfoote** [comment]
Kinetic targets Debian Jessie https://www.ros.org/reps/rep-0003.html#kinetic-kame-may-2016-may-2021 so cannot move forward to the new API. See #279  for past discussion. 

These macros are updated in the melodic branch, you can use that branch. Since this works for all the targeted platforms and there's newer branches targeted at your supported platform please consider using that. We generally don't want to add things for unsupported platforms if there's easy solutions to use them via a supported method.
