### ISSUE TITLE
use new rospy publisher syntax to avoid hanging

### ISSUE THREAD

**Issue by tfoote** [ros/geometry2#54]
Take advantage of: https://github.com/ros/ros_comm/issues/308

**Comment by tfoote** [comment]
Cherry picked into indigo: fd73a6fe446e04367767b645858a14790331f57d

**Comment by venabled** [comment]
Just as a heads up @tfoote , In order to publish high-rate transforms, or multiple transforms in a single callback I needed to increase the queue_size in the TransformBroadcaster class. Would recommend that you either increase queue size or allow it as a parameter to be passed into the class constructor.
