### ISSUE TITLE
Provide a way to clear tf2 buffers when the clock is reset

### ISSUE THREAD

**Issue by trainman419** [ros/geometry2#64]
When running a simulation or playing back a bag file with --clock, I often try to leave most of my nodes running, and only restart the thing that is publishing to /clock

Unfortunately, the tf2 internal buffer does not reset when /clock jumps backwards, and the tf2 subscribers don't have a manual mechanism to tell them that the clock has been reset, and they should clear their buffers.

See http://answers.ros.org/question/164026/how-can-i-reset-the-simulated-clock/ for more information.

**Comment by jbohren** [comment]
+100

**Comment by v4hn** [comment]
+1 In theory there should be a mechanism in place to _automatically_ clean the buffers when a loop is detected. I know this worked with tf by EOL in fuerte because I fixed it myself.
Also, I remember, @tfoote afterwards pushed some related changes for tf2.
I didn't investigate, but I currently have problems with tf2 and rosbag play --loop as well (current hydro).

**Comment by ZdenekM** [comment]
+1

**Comment by skohlbr** [comment]
+1

**Comment by tfoote** [comment]
duplicate #43
